# Instrucciones para Resolver Sistemas Ax=b y By=b

Se te proporciona una serie de tablas en la cual la última columna corresponde a un elemento conocido como **etiqueta**, y el resto de columnas se conoce como **características**. Tu tarea es llevar a cabo los siguientes pasos **sin el uso de funciones definidas (`def`)**, para que te familiarices con lo que sucede detrás al usar herramientas como scikit-learn de Python:

### 1. Descomponer las tablas
Descompón las tablas en:
- **Matriz A:** que contiene todas las características.
- **Vector b:** que contiene las etiquetas.

### 2. Generar la Matriz Ampliada B
Genera una matriz ampliada **B** añadiendo una primera columna de $1's$ y el resto con los valores de la matriz **A**, de modo que:
$$ B = [1|A] $$

### 3. Cálculo del Determinante
En los casos en que sea posible, calcula el determinante de las matrices **A** y **B**:
- Determinante de **A**: $ \text{det}(A) $
- Determinante de **B**: $ \text{det}(B) $

### 4. Cálculo del Rango
Calcula el rango de las matrices:
- **Rango de A**: $ \text{rank}(A) $
- **Rango de B**: $ \text{rank}(B) $

También, calcula el rango de las matrices ampliadas **[A|b]** y **[B|b]**:
$$ \text{rank}( [A|b] ) \quad \text{y} \quad \text{rank}( [B|b] ) $$

### 5. Clasificación de los Sistemas
Clasifica los sistemas:
- **Ax=b**
- **By=b**

según la clasificación de sistemas de ecuaciones lineales (determinado, indeterminado, o incompatible) basado en los rangos obtenidos.

### 6. Resolución de los Sistemas
Resuelve los sistemas utilizando:
- **Matriz inversa** si el sistema es determinado: $ x = A^{-1}b $
- **Pseudoinversa** en caso de ser un sistema indeterminado: $ x = A^{+}b $

Haz lo mismo para **B**:
$$ y = B^{-1}b \quad \text{o} \quad y = B^{+}b $$

### 7. Análisis de Estabilidad
Realiza un análisis de estabilidad de los sistemas a través de dilataciones y contracciones de las soluciones en factores del:
- $0.5\%$, $1\%$, $2\%$, $5\%$, y $10\%$.

Analiza los cambios porcentuales que se generan en las soluciones $b'$ perturbadas en relación con la $b$ real.

### 8. Intervalos de Confianza
Con el análisis anterior, establece una clase de intervalos de confianza en terminos de porcentaje para las soluciones obtenidas, considerando que:
- Las **dilataciones** podrían simular el redondeo o pérdida de precisión en los decimales de las soluciones.
- Las **contracciones** podrían simular errores numéricos pequeños o fluctuaciones en los datos originales.

### 9. Interpolantes
Las soluciones de los sistemas **Ax=b** y **By=b** pueden utilizarse para construir interpolantes:
- **Sin término independiente** para **Ax=b**.
- **Con término independiente** para **By=b**.

Construye dichos interpolantes.

### 10. Comparación de los Interpolantes
Analiza cuál de los interpolantes proporciona una solución más cercana a los valores de $b$, y argumenta si eso sería suficiente para justificar si es una mejor solución para el problema de interpolación.


In [144]:
import numpy as np
import time


In [145]:
# tabla (6x6)
tabla1 = np.array([[0.32047, 0.82356, 0.25645, 0.49580, 0.67355, 0.61427],
                  [0.29187, 0.44708, 0.19897, 0.89325, 0.73233, 0.89347],
                  [0.13883, 0.64831, 0.02541, 0.84798, 0.57868, 0.37958],
                  [0.89019, 0.36956, 0.23375, 0.45624, 0.18749, 0.25037],
                  [0.54278, 0.18745, 0.96885, 0.25942, 0.65492, 0.12485],
                  [0.76956, 0.06538, 0.49874, 0.82947, 0.86217, 0.78432]])


In [146]:
# tabla (6x6)
tabla2 = np.array([[0.42533, 0.30128, 0.67274, 0.56891, 0.84945, 0.61348],
                  [0.89747, 0.25390, 0.18011, 0.45375, 0.61618, 0.23765],
                  [0.53472, 0.74909, 0.10292, 0.92582, 0.42937, 0.97256],
                  [0.82625, 0.66803, 0.48776, 0.61463, 0.06765, 0.81539],
                  [0.16523, 0.81656, 0.41254, 0.72114, 0.82603, 0.15945],
                  [0.72064, 0.37514, 0.57535, 0.25643, 0.53927, 0.69474]])


In [147]:
# tabla (8x7)
tabla3 = np.array([[0.74898, 0.28122, 0.52920, 0.56900, 0.91599, 0.26114, 0.85767],
                  [0.87788, 0.57300, 0.21391, 0.18360, 0.27809, 0.47191, 0.52021],
                  [0.87446, 0.54117, 0.65085, 0.02731, 0.92548, 0.95857, 0.84126],
                  [0.44242, 0.31208, 0.45062, 0.48809, 0.24730, 0.08539, 0.49884],
                  [0.36721, 0.45338, 0.60793, 0.01837, 0.66224, 0.12615, 0.33194],
                  [0.54924, 0.69931, 0.05451, 0.81977, 0.56267, 0.36233, 0.99719],
                  [0.77000, 0.20419, 0.72319, 0.47703, 0.62884, 0.70215, 0.00228],
                  [0.59750, 0.39309, 0.90533, 0.88076, 0.34626, 0.56525, 0.59347]])


In [148]:
# tabla (8x7)
tabla4 = np.array([[0.43217, 0.27185, 0.63925, 0.14753, 0.65845, 0.72451, 0.92756],
                  [0.85973, 0.55467, 0.10348, 0.38429, 0.97862, 0.30109, 0.36874],
                  [0.18459, 0.66988, 0.47842, 0.82746, 0.13367, 0.93471, 0.74512],
                  [0.04917, 0.76520, 0.56264, 0.05618, 0.31561, 0.90881, 0.09857],
                  [0.70551, 0.97730, 0.84481, 0.27559, 0.12154, 0.54392, 0.64783],
                  [0.96104, 0.86563, 0.05429, 0.34809, 0.25537, 0.21155, 0.28367],
                  [0.57384, 0.78641, 0.19932, 0.14379, 0.47252, 0.20055, 0.18792],
                  [0.31864, 0.96378, 0.48521, 0.11467, 0.89523, 0.69090, 0.45634]])

In [149]:
# tabla (6x7)
tabla5 = np.array([[0.42074, 0.65412, 0.71950, 0.81775, 0.39471, 0.74543, 0.67315],
                  [0.12866, 0.89460, 0.56291, 0.21824, 0.99422, 0.40157, 0.58752],
                  [0.51278, 0.70214, 0.28451, 0.45349, 0.07861, 0.13209, 0.24194],
                  [0.89752, 0.67005, 0.46527, 0.84486, 0.87365, 0.26328, 0.45833],
                  [0.18930, 0.49567, 0.95384, 0.27422, 0.10112, 0.65198, 0.78461],
                  [0.36893, 0.76034, 0.01245, 0.21353, 0.07645, 0.84261, 0.03150]])


In [150]:
# tabla (8x7)
tabla6 = np.array([[0.74898, 0.28122, 0.52920, 0.56900, 0.91599, 0.26114, 0.85767],
                  [0.87788, 0.57300, 0.21391, 0.18360, 0.27809, 0.47191, 0.52021],
                  [0.87446, 0.54117, 0.65085, 0.02731, 0.92548, 0.95857, 0.84126],
                  [0.44242, 0.31208, 0.45062, 0.48809, 0.24730, 0.08539, 0.49884],
                  [0.36721, 0.45338, 0.60793, 0.01837, 0.66224, 0.12615, 0.33194],
                  [0.54924, 0.69931, 0.05451, 0.81977, 0.56267, 0.36233, 0.99719],
                  [0.77000, 0.20419, 0.72319, 0.47703, 0.62884, 0.70215, 0.00228],
                  [0.59750, 0.39309, 0.90533, 0.88076, 0.34626, 0.56525, 0.59347]])


### 1. Descomponer las tablas
Descompón las tablas en:
- **Matriz A:** que contiene todas las características.
- **Vector b:** que contiene las etiquetas.

In [151]:
def descomponer_tabla(tabla):
    A = tabla[:,:-1:]
    b = tabla[:,-1:]
    return A, b

In [152]:
A, b = descomponer_tabla(tabla1)
print( tabla1)
print(A)
print(b)

[[0.32047 0.82356 0.25645 0.4958  0.67355 0.61427]
 [0.29187 0.44708 0.19897 0.89325 0.73233 0.89347]
 [0.13883 0.64831 0.02541 0.84798 0.57868 0.37958]
 [0.89019 0.36956 0.23375 0.45624 0.18749 0.25037]
 [0.54278 0.18745 0.96885 0.25942 0.65492 0.12485]
 [0.76956 0.06538 0.49874 0.82947 0.86217 0.78432]]
[[0.32047 0.82356 0.25645 0.4958  0.67355]
 [0.29187 0.44708 0.19897 0.89325 0.73233]
 [0.13883 0.64831 0.02541 0.84798 0.57868]
 [0.89019 0.36956 0.23375 0.45624 0.18749]
 [0.54278 0.18745 0.96885 0.25942 0.65492]
 [0.76956 0.06538 0.49874 0.82947 0.86217]]
[[0.61427]
 [0.89347]
 [0.37958]
 [0.25037]
 [0.12485]
 [0.78432]]


### 2. Generar la Matriz Ampliada B
Genera una matriz ampliada **B** añadiendo una primera columna de $1's$ y el resto con los valores de la matriz **A**, de modo que:
$$ B = [1|A] $$

In [153]:
def Ampliada(A):
    return np.hstack((np.ones((A.shape[0], 1)), A))

# Ejemplo de uso
B = Ampliada(A)
print(B)

[[1.      0.32047 0.82356 0.25645 0.4958  0.67355]
 [1.      0.29187 0.44708 0.19897 0.89325 0.73233]
 [1.      0.13883 0.64831 0.02541 0.84798 0.57868]
 [1.      0.89019 0.36956 0.23375 0.45624 0.18749]
 [1.      0.54278 0.18745 0.96885 0.25942 0.65492]
 [1.      0.76956 0.06538 0.49874 0.82947 0.86217]]


### 3. Cálculo del Determinante
En los casos en que sea posible, calcula el determinante de las matrices **A** y **B**:
- Determinante de **A**: $ \text{det}(A) $
- Determinante de **B**: $ \text{det}(B) $

### 4. Cálculo del Rango
Calcula el rango de las matrices:
- **Rango de A**: $ \text{rank}(A) $
- **Rango de B**: $ \text{rank}(B) $

También, calcula el rango de las matrices ampliadas **[A|b]** y **[B|b]**:
$$ \text{rank}( [A|b] ) \quad \text{y} \quad \text{rank}( [B|b] ) $$

In [209]:
tablas = [ 
    {"datos" : tabla1, "nombre" : "tabla1"}, 
    {"datos" : tabla2, "nombre" : "tabla2"},
    {"datos" : tabla3, "nombre" : "tabla3"},
    {"datos" : tabla4, "nombre" : "tabla4"},
    {"datos" : tabla5, "nombre" : "tabla5"},
    {"datos" : tabla6, "nombre" : "tabla6"}
]

def np_det(A):
    try:
        return np.linalg.det(A)
    except np.linalg.LinAlgError as e:
        return None


def clasifica(rank_A, rank_A_b, n_A):
    # Segun documentacion de pag 9 de Interpolacion-Extrapolacion.pdf
    if rank_A == rank_A_b :
        if rank_A == n_A:
            return "Sistema Compatible Determinado (SCD)"
        elif rank_A < n_A:
            return "Sistema Compatible Indeterminado (SCI)"
    else:
        return "*** Sistema Incompatible (SIC)"

def analiza(A, b):
    det_A = np_det(A)
    det_A_b = np_det(np.hstack((A,b)))
    rank_A = np.linalg.matrix_rank(A)
    rank_A_b = np.linalg.matrix_rank(np.hstack((A,b)))
    n_A = len(A[0])
    clase = clasifica(rank_A, rank_A_b, n_A)
    print (
        "\tdet =", det_A, "\trank =", rank_A, "\tn =", n_A,"\trank(A|b) =", rank_A_b,
        "\n\tclase =", clase
        )
    return det_A, rank_A, det_A_b, rank_A_b, n_A, clase

for tabla in tablas:
    tabla["A"], tabla["b"] = descomponer_tabla(tabla["datos"])
    tabla["B"] = matriz_ampliada(tabla["A"])

    print ("\n#######",tabla["nombre"], "########") 
    print ("\n- Matriz A:", ) 
    analiza(tabla["A"], tabla["b"])
    print ("\n- Matriz B (ampliada):") 
    analiza(tabla["B"], tabla["b"])



####### tabla1 ########

- Matriz A:
	det = None 	rank = 5 	n = 5 	rank(A|b) = 6 
	clase = *** Sistema Incompatible (SIC)

- Matriz B (ampliada):
	det = -0.0016271442410992075 	rank = 6 	n = 6 	rank(A|b) = 6 
	clase = Sistema Compatible Determinado (SCD)

####### tabla2 ########

- Matriz A:
	det = None 	rank = 5 	n = 5 	rank(A|b) = 6 
	clase = *** Sistema Incompatible (SIC)

- Matriz B (ampliada):
	det = 0.004879188221007908 	rank = 6 	n = 6 	rank(A|b) = 6 
	clase = Sistema Compatible Determinado (SCD)

####### tabla3 ########

- Matriz A:
	det = None 	rank = 6 	n = 6 	rank(A|b) = 7 
	clase = *** Sistema Incompatible (SIC)

- Matriz B (ampliada):
	det = None 	rank = 7 	n = 7 	rank(A|b) = 8 
	clase = *** Sistema Incompatible (SIC)

####### tabla4 ########

- Matriz A:
	det = None 	rank = 6 	n = 6 	rank(A|b) = 7 
	clase = *** Sistema Incompatible (SIC)

- Matriz B (ampliada):
	det = None 	rank = 7 	n = 7 	rank(A|b) = 8 
	clase = *** Sistema Incompatible (SIC)

####### tabla5 ########



In [155]:
def determinante(A):
    # Verificar si la matriz es cuadrada
    if len(A) != len(A[0]):
        raise ValueError("La matriz no es cuadrada")

    # Caso base: matriz 2x2
    if len(A) == 2:
        return A[0][0] * A[1][1] - A[0][1] * A[1][0]

    # Caso general: matriz nxn
    det = 0
    for i in range(len(A)):
        # Crear la submatriz
        submatriz = [row[:i] + row[i+1:] for row in A[1:]]
        # Calcular la determinante de la submatriz
        det_submatriz = calcular_determinante(submatriz)
        # Actualizar la determinante
        det += ((-1) ** i) * A[0][i] * det_submatriz

    return det



In [156]:
# Definir la matriz
A = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [157]:
# Calcular la determinante
start_time = time.time()
det_A = determinante(tabla1.tolist())
end_time = time.time()
print("El tiempo de ejecución es:", end_time - start_time)
print("La determinante de la matriz con funct es:", det_A)


# Definir la matriz
A = np.array(A)

# Calcular la determinante
start_time = time.time()
det_A = np.linalg.det(tabla1)
end_time = time.time()
print("El tiempo de ejecución es:", end_time - start_time)
print("La determinante de la matriz con numpy es:", det_A)

El tiempo de ejecución es: 0.0003466606140136719
La determinante de la matriz con funct es: -0.048310267254011885
El tiempo de ejecución es: 6.532669067382812e-05
La determinante de la matriz con numpy es: -0.048310267254011906


In [158]:
def rango(A):
    # Convertir la matriz a una lista de listas
    A = [fila[:] for fila in A]

    # Calcular el número de filas y columnas
    num_filas = len(A)
    num_cols = len(A[0])

    # Realizar la eliminación gaussiana
    for i in range(num_filas):
        # Buscar un pivote no nulo
        pivote = i
        while pivote < num_filas and A[pivote][i] == 0:
            pivote += 1

        # Si no se encontró un pivote no nulo, la columna es linealmente dependiente
        if pivote == num_filas:
            continue

        # Intercambiar filas
        A[i], A[pivote] = A[pivote], A[i]

        # Normalizar la fila
        factor = A[i][i]
        A[i] = [x / factor for x in A[i]]

        # Eliminar la variable de las demás filas
        for j in range(num_filas):
            if j != i:
                factor = A[j][i]
                A[j] = [xj - factor * xi for xj, xi in zip(A[j], A[i])]

    # El rango es el número de filas no nulas
    ret_rango = sum(1 for fila in A if any(x != 0 for x in fila))

    return ret_rango



In [159]:
# Ejemplo de uso
A = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print(rango(A))  # Salida: 2

# Calcular el rango de la matriz
rang = np.linalg.matrix_rank(A)

print("El rango de la matriz A es:", rang)


2
El rango de la matriz A es: 2


In [160]:
# Calcular la determinante
start_time = time.time()
rang_A = rango(tabla1.tolist())
end_time = time.time()
print("El tiempo de ejecución es:", end_time - start_time)
print("La determinante de la rango con funct es:", rang_A)


# Definir la matriz
A = np.array(A)

# Calcular la determinante
start_time = time.time()
rang_A = np.linalg.matrix_rank(tabla1)
end_time = time.time()
print("El tiempo de ejecución es:", end_time - start_time)
print("La determinante de la marangotriz con numpy es:", rang_A)

El tiempo de ejecución es: 5.841255187988281e-05
La determinante de la rango con funct es: 6
El tiempo de ejecución es: 0.000152587890625
La determinante de la marangotriz con numpy es: 6
